### ISSUE TITLE
Slurm role fails when installing "install" from scratch

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-slurm#44]
- name: restart and enable slurmdbd
    service: name=slurmdbd state=restarted enabled=yes

Above task in dbd.yml playbook needs a "slurm" user to be successful.
Slurm user is created in service.yml which comes after dbd.yml in main.yml.

Reporter: Sami Maisala

Quick fix: 

Copy the two tasks from service.yml and paste them just before the "restart and enable slurmdbd" task in roles/ansible-role-slurm/tasks/dbd.yml
Like this:

- name: add slurm unix group
group: name=slurm system=no state=present
register: reg_slurm_unixgroup

- name: add slurm unix user
user: name=slurm shell=/sbin/nologin createhome=no system=no append=yes group=slurm state=present
register: reg_slurm_unixuser

- name: restart and enable slurmdbd
service: name=slurmdbd state=restarted enabled=yes

**Comment by martbhell** [comment]
Two notes:
 - Consistent UID/GID is important.
 - This error was seen on a site that runs the slurmdbd on the same node as slurmctld (install)

**Comment by martbhell** [comment]
Since this issue we have added a task in tasks/dbd.yml to create the unix group and user called slurm. Without this slurm wouldn't run because there was no slurm user available. However this brings up an issue when the dbd and slurm_service_node host are **different** - in that case the slurm unix user's UID/GID will most likely be different. This is bad [1].

We could add a task which is delegated to the dbd host inside the service.yml which starts the slurmdbd service on the dbd host (before the sacctmgr commands and the slurmctld start but after the user was created on the service node). And then remove creating the slurm user on the dbd.yml.

We could perhaps also add assert slurm user exists in the compute.yml.

[1]: http://slurm.schedmd.com/slurmdbd.conf.html

**Comment by martbhell** [comment]
Installing from scratch appears to be working. Closing this as fixed now. If the issue re-surfaces we can open a new one.
