### ISSUE TITLE
Only restart munge and slurmd if something has changed.

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-slurm#7]
We should only restart if something changes.

https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/blob/master/tasks/compute.yml#L19

**Comment by martbhell** [comment]
And we should change very few things by default. Perhaps only make sure that the slurm.conf.j2 and munge.key are installed?

**Comment by martbhell** [comment]
Care must be taken that things are done in the right order.
Using notifiers to restart the slurm services (slurm, slurmd, slurmdbd, more?) at the end of the playbook may not be what we want in several cases. For example the slurmdbd must be up and have its changes applied before the sacctmgr commands are executed. 

Munge is fairly safe as it's basically just copying in a file.

**Comment by jabl** [comment]
Also, in many cases when slurm.conf has been updated it's sufficient to run "scontrol reconfigure" on a single node, rather than restarting slurmctld and slurmd's everywhere. Problem is, it's not very clear when this is sufficient and when a full restart is needed. Some of the cases are mentioned in the man pages, but IIRC there is nothing like, say, "scontrol reconfigure" returning an error saying "sorry, restart needed". :(

**Comment by martbhell** [comment]
It's possible [1] to flush the handlers in the middle of a play.

Example:
<pre>
tasks:
   - shell: configure slurmdbd
   - meta: flush_handlers
   - shell: run sacctmgr commands
</pre>

[1]: http://docs.ansible.com/ansible/playbooks_intro.html#handlers-running-operations-on-change
