### ISSUE TITLE
slurm_backup_controller and statedir

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-slurm#80]
While doing some deeper testing of PRs #75 and #78  I ran into some issues with the NFS in my test setup, first one was that the statedir was a link and not a directory. 
In the end I mounted the NFS one directory up at /opt/slurmdb and then tmp was a directory and things worked. 

This mountpoint needs to be there before slurmctld. 
Setting up the statedir for HA is not covered by fgci-ansible or this role though.
Should it be?

**test details:**

changes in test/test.yml:
<pre>
vars:
     - slurm_service_node: "slurm-1"
     - slurm_backup_controller: "slurm-2"
</pre>

an inventory like this:
<pre>
[install]
IP1 ansible_ssh_user=cloud-user
IP2 ansible_ssh_user=cloud-user
</pre>

ansible did what was expected - it only ran dbd.yml on slurm_service_node and not on the slurm_backup_controller.

Also managed to get takeovers working, reducing slurmctldtimeout helped while doing that so I also reduced that in the test/test.yml playbook

**Comment by jabl** [comment]
Yes, it maybe should be spelled out in README.md or defaults/main.yml that if you want a backup controller, then you need to make sure that the statesave directory is in a location accessible by both primary and backup controllers (and preferably HA as well...). It's spelled out in the slurm docs, but I guess it bears repeating here too...

Personally, I find the entire slurm HA design quite kludgy, with using a shared directory instead of, say, pushing the state from master->slave, or using something like etcd or whatnot.

**Comment by martbhell** [comment]
Added some pointers to the README.
Adding these into the next release on this role.
